# Generated by Django 3.1.2 on 2020-11-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameboards',
            old_name='board',
            new_name='check_board',
        ),
        migrations.AddField(
            model_name='gameboards',
            name='game_board',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
